#!/bin/bash

export GPHOME=/opt/gphoto2.5
export PATH=$GPHOME/bin:$PATH
export LD_LIBRARY_PATH=$GPHOME/lib
export PKG_CONFIG_PATH=$GPHOME/lib/pkgconfig
export LD_RUN_PATH=$LD_LIBRARY_PATH

./configure --without-aalib --prefix=$GPHOME 

