#!/bin/bash

sudo apt install build-essential cmake pkg-config \
	libjpeg-dev libtiff5-dev libjasper-dev libpng12-dev \
	libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
	libxvidcore-dev libx264-dev \
	gfortran ant
