#!/bin/bash

rm -fr opencv-3*
tar xf 3.4.6.tar.gz

mkdir -p opencv-3.4.6/build
cd opencv-3.4.6/build

cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=OFF \
    -D BUILD_EXAMPLES=OFF ..
