package l9g.photobox.cv;

//~--- non-JDK imports --------------------------------------------------------

import org.slf4j.LoggerFactory;

/**
 * Class description
 *
 *
 * @version        $version$, 18/08/24
 * @author         Dr. Thorsten Ludewig <t.ludewig@gmail.com>
 */
public class BaseFrame extends javax.swing.JFrame
{

  /** Field description */
  private final static org.slf4j.Logger LOGGER = LoggerFactory.getLogger(
    BaseFrame.class.getName());

  //~--- constructors ---------------------------------------------------------

  /**
   * Creates new form BaseFrame
   */
  public BaseFrame()
  {
    initComponents();
    initAdditionalComponents();
  }

  //~--- methods --------------------------------------------------------------

  /**
   * Method description
   *
   *
   * @param evt
   */
  private void formWindowOpened(java.awt.event.WindowEvent evt)
  {
    LOGGER.debug("BaseFrame opened");
    viewPortPanel.startUpdate();
  }

  /**
   * Method description
   *
   */
  private void initAdditionalComponents()
  {
    viewPortPanel = new ViewPortPanel();
    getContentPane().add(viewPortPanel, java.awt.BorderLayout.CENTER);
    pack();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(java.awt.Color.black);
    addWindowListener(new java.awt.event.WindowAdapter()
    {
      public void windowOpened(java.awt.event.WindowEvent evt)
      {
        formWindowOpened(evt);
      }
    });

    pack();
  }// </editor-fold>//GEN-END:initComponents

  //~--- fields ---------------------------------------------------------------

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

  /** Field description */
  private ViewPortPanel viewPortPanel;
}
